const HELP_TEXT = {
  general: [
    'Usage: think "raw thought"',
    '       think --ingest',
    '       think --recent [--count=N] [--query=TEXT]',
    '       think --remember [--brief] [--limit=N] [query]',
    '       think --stats [--since=DURATION] [--from=DATE] [--to=DATE] [--bucket=hour|day|week]',
    '       think --prompt-metrics [--since=DURATION] [--from=DATE] [--to=DATE] [--bucket=hour|day|week]',
    '       think --browse[=<entryId>]',
    '       think --inspect=<entryId>',
    '       think --reflect[=<entryId>] [--mode=challenge|constraint|sharpen]',
    '       think --reflect-session=<sessionId> <response>',
    '       think --migrate-graph',
    '',
    'Global options:',
    '  --help, -h   Show help',
    '  --json       Emit JSONL output',
    '  --verbose    Emit JSONL trace events on stderr',
    '',
    'Command help:',
    '  think --recent --help',
    '  think recent --help',
    '  think --inspect -h',
    '',
    'To capture text that starts with a dash, end option parsing first:',
    '  think -- "-h"',
  ].join('\n'),
  capture: [
    'Usage: think "raw thought"',
    '       think -- "<text that starts with a dash>"',
    '',
    'Capture saves raw text exactly as written.',
    'No classification, tagging, or retrieval happens before write.',
  ].join('\n'),
  ingest: [
    'Usage: think --ingest',
    '',
    'Capture stdin explicitly.',
    'Without --ingest, piped input is ignored to avoid accidental capture.',
  ].join('\n'),
  recent: [
    'Usage: think --recent [--count=N] [--query=TEXT]',
    '',
    'List raw captures newest first.',
    '',
    'Options:',
    '  --count=N     Limit output to the newest N entries',
    '  --query=TEXT  Filter entries by case-insensitive text match',
  ].join('\n'),
  remember: [
    'Usage: think --remember [--brief] [--limit=N] [query]',
    '',
    'Recall context from prior captures using ambient project receipts or an explicit query.',
    '',
    'Options:',
    '  --brief       Show a one-line snippet per match',
    '  --limit=N     Return at most N matches',
  ].join('\n'),
  stats: [
    'Usage: think --stats [--since=DURATION] [--from=DATE] [--to=DATE] [--bucket=hour|day|week]',
    '',
    'Summarize capture counts over time.',
    '',
    'Options:',
    '  --since=DURATION  Relative window such as 24h, 7d, or 2w',
    '  --from=DATE       Absolute lower bound',
    '  --to=DATE         Absolute upper bound',
    '  --bucket=PERIOD   Group by hour, day, or week',
  ].join('\n'),
  'prompt-metrics': [
    'Usage: think --prompt-metrics [--since=DURATION] [--from=DATE] [--to=DATE] [--bucket=hour|day|week]',
    '',
    'Read macOS capture panel telemetry.',
    '',
    'Options:',
    '  --since=DURATION  Relative window such as 24h, 7d, or 2w',
    '  --from=DATE       Absolute lower bound',
    '  --to=DATE         Absolute upper bound',
    '  --bucket=PERIOD   Group by hour, day, or week',
  ].join('\n'),
  browse: [
    'Usage: think --browse',
    '       think --browse=<entryId>',
    '',
    'Open the interactive browser in a TTY or inspect a specific entry with browse context.',
  ].join('\n'),
  inspect: [
    'Usage: think --inspect=<entryId>',
    '',
    'Show exact metadata and derived receipts for a single capture.',
  ].join('\n'),
  reflect: [
    'Usage: think --reflect',
    '       think --reflect=<entryId> [--mode=challenge|constraint|sharpen]',
    '',
    'Start a reflect session from an interactive picker or a specific seed entry.',
    '',
    'Options:',
    '  --mode=TYPE   Use challenge, constraint, or sharpen prompts',
  ].join('\n'),
  'reflect-session': [
    'Usage: think --reflect-session=<sessionId> <response>',
    '',
    'Reply to an existing reflect session and store the derived response entry.',
  ].join('\n'),
  'migrate-graph': [
    'Usage: think --migrate-graph',
    '',
    'Backfill additive graph edges required by newer read surfaces.',
  ].join('\n'),
};

export function renderHelp(topic) {
  const resolvedTopic = HELP_TEXT[topic] ? topic : 'general';
  return {
    topic: resolvedTopic,
    message: HELP_TEXT[resolvedTopic],
  };
}
